services:
  ollama:
    image: docker.io/ollama/ollama:rocm
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - /models:/root/.ollama/models:Z
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    environment:
      - HSA_OVERRIDE_GFX_VERSION=11.0.0
      - OLLAMA_HOST=0.0.0.0:11434
